# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: NCSOFT DANBI
subtitle: "A simple yet classy theme for your Jekyll website or blog"
email: danbi@ncsoft.com
name: NCSOFT DANBI
description: >
  NCSOFT 데이터 분석 기술 공유 블로그.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://danbi-ncsoft.github.io/" # the base hostname & protocol for your site
cover: "/assets/danbi2.jpg"
logo: "/assets/main_ci.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
  layout: 'archive'
  permalinks:
    category: '/category/:name/'

# Disqus comments
disqus_shortname: danbi

# Google analytics
ga_tracking_id: "UA-122517055-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: Competition
    desc: "경진대회 관련 포스트"

  - cat: Works
    desc: "분석 업무 관련 자료"

  - cat: ETC
    desc: "그 외 기타 자료"

  - cat: Study
    desc: "팀 스터디 자료"    
# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:

  - name: GitHub
    icon: github
    url: https://github.com/danbi-ncsoft
    desc: Go to GitHub
    share: false
    
  - name: RSS
    icon: rss
    url: https://danbi-ncsoft.github.io/feed.xml
    desc: Subscribe via RSS
    share: false


# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
#    fb_image: "/assets/danbi2.jpg"
#    fb_image_width: 612
#    fb_image_height: 605
#    fb_image_type: "image/jpg"

#    twitter_image: "/assets/danbi2.jpg"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
